### PR TITLE
Fix etcd packages

### PR DESCRIPTION
**Pull request by SunSince90**
This commit updates etcd go packages to a stable version.

Before this, the project was using a workaround -- by using `replace` -- that was taken from Kubernetes' code. This was because the official package had some dependency problems that was also conflicting with our dependencies. These issue are solved and so I am now getting rid of the `replace` workaround and update our modules to use the stable version of etcd's packages.

### CODE REVIEW

**Comment by SunSince90** [comment]
Just a note: please review and merge the other PR before this one -- the one that fixes context deadline (I don't want to make link references to it to keep them clean :D )

**Comment by ljakab** [comment]
> Just a note: please review and merge the other PR before this one -- the one that fixes context deadline (I don't want to make link references to it to keep them clean :D )

I did. I guess this one needs a rebase now, as GitHub reports conflicts now.

**Comment by SunSince90** [comment]
> > Just a note: please review and merge the other PR before this one -- the one that fixes context deadline (I don't want to make link references to it to keep them clean :D )
> 
> I did. I guess this one needs a rebase now, as GitHub reports conflicts now.

thank you! Yes the conflict is because this one doesn't use the same version of the `servicedirectory` package, so I just need to rebase and accept the existing change for those lines

**Comment by SunSince90** [comment]
Rebased and ready to be merged :)

**Review by ljakab — APPROVED** [review]

**Pull request merged**
